name: shopping_explore
description: "ShoppingExplore cross-platform mobile application for iOS and Android."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any

  # UI & Typography
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Architecture & Utility
  equatable: ^2.0.5

  url_launcher: any
  uuid: any
  image_picker: ^1.1.2
  path_provider: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

